# Generated by Django 2.2.12 on 2022-06-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sur_name', models.CharField(max_length=150)),
                ('mid_name', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=150)),
                ('matric_no', models.CharField(max_length=35)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('level', models.CharField(choices=[('LEVEL', 'Level'), ('200', '200'), ('300', '300'), ('400', '400')], max_length=5)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('faculty', models.CharField(choices=[('FACULTY', 'Faculty'), ('HUMANITIES', 'Faculty of Humanities'), ('SMS', 'Faculty of Social and Management Sciences'), ('SCIENCE', 'Faculty of Science and Science Education')], max_length=5)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
